// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojhghmadkdllnqcqpbhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qaGdobWFka2RsbG5xY3FwYmhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MTIxNjIsImV4cCI6MjA2MTM4ODE2Mn0.XPTye6t0qYcIYeAW81hvPUW-ZwHL8x-Gb_-QyOTW3Vk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);